[workspace]
authors = ["MatteoGuglielmi-Tech <matteo.guglielmi.ma.gu@gmail.com>"]
channels = ["conda-forge"]
name = "notify_bot"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"
python-telegram-bot = ">=22.3,<23"
python-dotenv = ">=1.1.1,<2"

[pypi-dependencies]
rich = ">=14.2.0, <15"
psycopg2-binary = ">=2.9.11, <3"

[feature.dev.dependencies]
debugpy = "*"
tk = "*"

[environments]
dev = { features = ["dev"], solve-group = "default" }
